"""
weak_labeller.py
================
Generates pseudo-labels for XGBoost training in the absence of ground-truth
analyst labels.  Labels are generated by deterministic heuristic rules.
Each label includes a confidence score.

Rules (R01–R07):
  R01  rolling_7d_autoclose_rate > 0.80                     → false_break=1, conf=0.85
  R02  offsetting_break_exists = True                       → false_break=1, conf=0.90
  R03  is_statistical_outlier = True AND break_age_days < 3 → false_break=1, conf=0.75
  R04  csa_margin_call_flag = True AND break_age_days < 2   → false_break=1, conf=0.80  (OTC)
  R05  coupon_payment_proximity < 3 AND break_age_days < 3  → false_break=1, conf=0.80  (MTN)
  R06  div_ex_date_proximity < 3 AND break_age_days < 3     → false_break=1, conf=0.80  (CEQ)
  R07  governance_completeness_score = 1.0 AND age > 90     → false_break=0, conf=0.70
  R08  no rule matched                                      → NaN (excluded from training)

Priority: earlier rules take precedence (first match wins).
"""

from __future__ import annotations

import logging
from typing import Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def label_breaks(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply R01–R07 labelling rules to the feature matrix (or DQ-scored df).
    Adds two columns:
      pseudo_label       (1=false_break, 0=genuine, NaN=unlabelled)
      label_confidence   (0–1 float, NaN for unlabelled)

    Returns augmented DataFrame (copy).
    """
    df = df.copy()
    n   = len(df)
    lbl = np.full(n, np.nan)
    conf = np.full(n, np.nan)

    # Resolve feature series with safe fallbacks
    age         = _num(df, "break_age_days")
    autoclose   = _num(df, "rolling_7d_autoclose_rate")
    offsetting  = _bool(df, "offsetting_break_exists")
    is_outlier  = _bool(df, "is_statistical_outlier")
    csa_flag    = _bool(df, "csa_margin_call_flag")
    coupon_prox = _num(df, "coupon_payment_proximity")
    div_prox    = _num(df, "div_ex_date_proximity")
    gov_score   = _num(df, "governance_completeness_score")
    ac          = df.get("asset_class", pd.Series("", index=df.index)).fillna("")

    # ── R01 ────────────────────────────────────────────────────────────────
    r01 = autoclose > 0.80
    _apply(lbl, conf, r01, label=1, confidence=0.85)

    # ── R02 ────────────────────────────────────────────────────────────────
    r02 = offsetting & ~r01
    _apply(lbl, conf, r02, label=1, confidence=0.90)

    # ── R03 ────────────────────────────────────────────────────────────────
    r03 = is_outlier & (age < 3) & ~r01 & ~r02
    _apply(lbl, conf, r03, label=1, confidence=0.75)

    # ── R04 (OTC only) ─────────────────────────────────────────────────────
    r04 = csa_flag & (age < 2) & (ac == "OTC") & ~r01 & ~r02 & ~r03
    _apply(lbl, conf, r04, label=1, confidence=0.80)

    # ── R05 (MTN only) ─────────────────────────────────────────────────────
    r05 = (coupon_prox < 3) & (age < 3) & (ac == "MTN") & ~r01 & ~r02 & ~r03 & ~r04
    _apply(lbl, conf, r05, label=1, confidence=0.80)

    # ── R06 (CEQ only) ─────────────────────────────────────────────────────
    r06 = (div_prox < 3) & (age < 3) & (ac == "CEQ") & ~r01 & ~r02 & ~r03 & ~r04 & ~r05
    _apply(lbl, conf, r06, label=1, confidence=0.80)

    # ── R07 — genuine break (governance complete + aged) ───────────────────
    r07 = (gov_score >= 1.0) & (age > 90) & ~r01 & ~r02 & ~r03 & ~r04 & ~r05 & ~r06
    _apply(lbl, conf, r07, label=0, confidence=0.70)

    # R08: remainder stays NaN

    df["pseudo_label"]      = lbl
    df["label_confidence"]  = conf

    labelled = int((~np.isnan(lbl)).sum())
    logger.info(
        "Pseudo-labelling complete: %d/%d rows labelled "
        "(%.1f%% false_break, %.1f%% genuine)",
        labelled, n,
        float(np.nansum(lbl == 1) / max(labelled, 1) * 100),
        float(np.nansum(lbl == 0) / max(labelled, 1) * 100),
    )
    return df


def get_training_set(
    df: pd.DataFrame,
    min_confidence: float = 0.75,
) -> pd.DataFrame:
    """
    Filter to rows where pseudo_label is not NaN and confidence >= min_confidence.
    Returns a copy suitable for XGBoost training.
    """
    if "pseudo_label" not in df.columns:
        df = label_breaks(df)

    mask = (
        df["pseudo_label"].notna() &
        df["label_confidence"].fillna(0) >= min_confidence
    )
    result = df[mask].copy()
    logger.info(
        "Training set: %d rows (min_confidence=%.2f)", len(result), min_confidence
    )
    return result


def get_label_summary(df: pd.DataFrame) -> dict:
    """Return a summary of pseudo-label coverage."""
    if "pseudo_label" not in df.columns:
        return {}

    lbl = df["pseudo_label"]
    total = len(lbl)
    n_false  = int((lbl == 1).sum())
    n_genuine = int((lbl == 0).sum())
    n_unlabelled = int(lbl.isna().sum())

    return {
        "total":       total,
        "false_break": n_false,
        "genuine":     n_genuine,
        "unlabelled":  n_unlabelled,
        "labelled_pct": round((n_false + n_genuine) / max(total, 1) * 100, 1),
    }


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _num(df: pd.DataFrame, col: str) -> "np.ndarray":
    """Return column as float array; NaN if missing."""
    if col in df.columns:
        return pd.to_numeric(df[col], errors="coerce").fillna(np.nan).to_numpy()
    return np.full(len(df), np.nan)


def _bool(df: pd.DataFrame, col: str) -> "np.ndarray":
    """Return column as boolean array; False if missing."""
    if col in df.columns:
        v = df[col]
        if v.dtype == bool or v.dtype == "bool":
            return v.to_numpy()
        return pd.to_numeric(v, errors="coerce").fillna(0).astype(bool).to_numpy()
    return np.zeros(len(df), dtype=bool)


def _apply(
    lbl: "np.ndarray",
    conf: "np.ndarray",
    mask: "np.ndarray",
    label: int,
    confidence: float,
) -> None:
    """Set label and confidence where mask is True AND label not already set."""
    idx = np.where(mask & np.isnan(lbl))[0]
    lbl[idx]  = float(label)
    conf[idx] = confidence
