import axios from 'axios'
const api = axios.create({ baseURL: '/api', timeout: 120_000 })
export const getSummary = (p) => api.get('/dashboard/summary', { params: p })
export const getPlatformBreakdown = (p) => api.get('/dashboard/platform-breakdown', { params: p })
export const getAgeProfile = (p) => api.get('/dashboard/age-profile', { params: p })
export const getResolutionTrend = (days=30) => api.get('/dashboard/resolution-trend', { params: { days } })
export const getAssetClassBreakdown = () => api.get('/dashboard/asset-class-breakdown')
export const getBreaks = (p) => api.get('/breaks', { params: p })
export const getMaterialBreaks = () => api.get('/breaks/material')
export const getEmirBreaks = () => api.get('/breaks/emir')
export const getBreaksByRec = (id) => api.get(`/breaks/by-rec/${id}`)
export const getRecs = () => api.get('/recs')
export const getRecDetail = (id) => api.get(`/recs/${id}`)
export const getJiraCoverage = () => api.get('/jira/coverage')
export const getJiraDrafts = () => api.get('/jira/drafts')
export const approveJiraDraft = (ref) => api.post(`/jira/approve/${ref}`)
export const getJiraEpics = () => api.get('/jira/epics')
export const getCoverageGap = () => api.get('/jira/coverage-gap')
export const getThemeSummary = () => api.get('/themes/summary')
export const getThemeTrend = (days=30) => api.get('/themes/trend', { params: { days } })
export const getThemeCrosswalk = () => api.get('/themes/crosswalk')
export const uploadFile = (uploadType, file, sourceType=null) => {
  const fd = new FormData(); fd.append('file', file)
  if (sourceType) fd.append('source_type', sourceType)
  return api.post(`/upload/${uploadType}`, fd, { headers: { 'Content-Type': 'multipart/form-data' } })
}
export const getUploadLog = () => api.get('/upload/log')
export const getUploadStatus = (id) => api.get(`/upload/status/${id}`)
export const runPipeline = () => api.post('/pipeline/run')
export const getPipelineStatus = () => api.get('/pipeline/status')
export default api
