import os, yaml
OUT_DIR = os.path.join(os.path.dirname(__file__), "rec_configs")
os.makedirs(OUT_DIR, exist_ok=True)
TLM_RECS = [
    ("Cash Equity Settlement Recon","Cash Equities"),("Cash Equity Price Break Recon","Cash Equities"),("Cash Equity FX Recon","Cash Equities"),("Cash Equity Nostro Recon","Cash Equities"),("Cash Equity Corporate Action Recon","Cash Equities"),("Equity Custody Position Recon","Cash Equities"),("Equity Client Position Recon","Cash Equities"),("Equity Prime Brokerage Recon","Cash Equities"),("Equity CCP Settlement Recon","Cash Equities"),("Equity Dividend Recon","Cash Equities"),
    ("LnD Accrual Recon","Loans & Deposits"),("LnD Principal Balance Recon","Loans & Deposits"),("LnD Rate Fixing Recon","Loans & Deposits"),("LnD Day Count Recon","Loans & Deposits"),("LnD Maturity Date Recon","Loans & Deposits"),("Repo Collateral Recon","Loans & Deposits"),("Reverse Repo Recon","Loans & Deposits"),("Securities Lending Recon","Loans & Deposits"),("Cash Collateral Recon","Loans & Deposits"),("Term Deposit Recon","Loans & Deposits"),
    ("MTN Coupon Recon","Medium Term Notes"),("MTN Notional Recon","Medium Term Notes"),("MTN Amortisation Recon","Medium Term Notes"),("MTN CUSIP Reference Recon","Medium Term Notes"),("MTN Day Count Convention Recon","Medium Term Notes"),("Structured Note Recon","Medium Term Notes"),("Floating Rate Note Recon","Medium Term Notes"),("Zero Coupon Bond Recon","Medium Term Notes"),("Callable Bond Recon","Medium Term Notes"),("Inflation Linked Recon","Medium Term Notes"),
    ("IRS NPV Recon","OTC Derivatives"),("CDS Spread Recon","OTC Derivatives"),("FX Option Premium Recon","OTC Derivatives"),("TRS Notional Recon","OTC Derivatives"),("Swaption Recon","OTC Derivatives"),("Credit Default Swap Recon","OTC Derivatives"),("Equity Swap Recon","OTC Derivatives"),("FX Forward Recon","OTC Derivatives"),("Commodity Swap Recon","OTC Derivatives"),("OTC Margin Dispute Recon","OTC Derivatives"),
    ("FX Spot Nostro Recon","Cash Equities"),("FX Forward Nostro Recon","Cash Equities"),("EM Equity Recon","Cash Equities"),("Fixed Income Settlement Recon","Medium Term Notes"),("Government Bond Recon","Medium Term Notes"),("Corporate Bond Recon","Medium Term Notes"),("High Yield Bond Recon","Medium Term Notes"),("Covered Bond Recon","Medium Term Notes"),("ABS Position Recon","Medium Term Notes"),("MBS Recon","Medium Term Notes"),
    ("Equity Option Recon","OTC Derivatives"),("Index Future Recon","OTC Derivatives"),("Interest Rate Future Recon","OTC Derivatives"),("Bond Future Recon","OTC Derivatives"),("Currency Future Recon","OTC Derivatives"),("Overnight Index Swap Recon","Loans & Deposits"),("SONIA Rate Recon","Loans & Deposits"),("SOFR Rate Recon","Loans & Deposits"),("EURIBOR Rate Recon","Loans & Deposits"),("Prime Loan Recon","Loans & Deposits"),
    ("Bilateral Repo Recon","Loans & Deposits"),("Triparty Repo Recon","Loans & Deposits"),("Commercial Paper Recon","Medium Term Notes"),("Certificate of Deposit Recon","Medium Term Notes"),("EMTN Programme Recon","Medium Term Notes"),("Sukuk Recon","Medium Term Notes"),("Convertible Bond Recon","Medium Term Notes"),("Preferred Share Recon","Cash Equities"),("ETF Position Recon","Cash Equities"),("ADR/GDR Recon","Cash Equities"),
    ("Rights Issue Recon","Cash Equities"),("Warrants Recon","Cash Equities"),("Delta One Recon","OTC Derivatives"),("Variance Swap Recon","OTC Derivatives"),("Dividend Swap Recon","OTC Derivatives"),("Volatility Swap Recon","OTC Derivatives"),("CDS Index Recon","OTC Derivatives"),("CLO Recon","Medium Term Notes"),("CDO Recon","Medium Term Notes"),("Structured Finance Recon","Medium Term Notes"),
    ("Mortgage Backed Recon","Medium Term Notes"),("Prime Broker Cash Recon","Loans & Deposits"),("Syndicated Loan Recon","Loans & Deposits"),("Subordinated Debt Recon","Loans & Deposits"),("Tier 1 Capital Recon","Loans & Deposits"),
]
ASSET_RULES = {
    "Cash Equities":     {"pct":0.005,"abs":300000,"sla":3,"epic":"EQ-BREAKS", "emir":False,"model":"rf_ceq","self_correct":2},
    "Loans & Deposits":  {"pct":0.001,"abs":500000,"sla":5,"epic":"LND-BREAKS","emir":False,"model":"rf_lnd","self_correct":0},
    "Medium Term Notes": {"pct":0.002,"abs":750000,"sla":7,"epic":"MTN-BREAKS","emir":False,"model":"rf_mtn","self_correct":3},
    "OTC Derivatives":   {"pct":0.0005,"abs":250000,"sla":1,"epic":"OTC-BREAKS","emir":True, "model":"rf_otc","self_correct":0},
}
for i,(rec_name,asset_class) in enumerate(TLM_RECS,start=1):
    r=ASSET_RULES[asset_class]; rec_id=f"TLM_REC_{i:03d}"
    with open(os.path.join(OUT_DIR,f"{rec_id}.yaml"),"w") as f:
        yaml.dump({"rec_id":rec_id,"rec_name":rec_name,"source_platform":"TLM","asset_class":asset_class,"d3s_asset_class":None,"threshold_type":"HYBRID","threshold_pct":r["pct"],"threshold_abs_gbp":r["abs"],"escalation_sla_days":r["sla"],"jira_epic":r["epic"],"emir_flag":r["emir"],"self_correct_days":r["self_correct"],"ml_model_id":r["model"],"active":True},f)
DUCO_RECS=[("DUCO Equity Position Recon","Cash Equities"),("DUCO Credit Position Recon","OTC Derivatives"),("DUCO Rates Position Recon","Loans & Deposits"),("DUCO FX Position Recon","Cash Equities"),("DUCO Commodity Position Recon","OTC Derivatives"),("DUCO Prime Broker Recon","Cash Equities"),("DUCO Fixed Income Recon","Medium Term Notes"),("DUCO Collateral Recon","OTC Derivatives"),("DUCO Cash Management Recon","Loans & Deposits"),("DUCO Derivatives Margin Recon","OTC Derivatives")]
for i,(rec_name,asset_class) in enumerate(DUCO_RECS,start=1):
    r=ASSET_RULES[asset_class]; rec_id=f"DUCO_REC_{i:03d}"
    with open(os.path.join(OUT_DIR,f"{rec_id}.yaml"),"w") as f:
        yaml.dump({"rec_id":rec_id,"rec_name":rec_name,"source_platform":"DUCO","asset_class":asset_class,"d3s_asset_class":None,"threshold_type":"HYBRID","threshold_pct":r["pct"],"threshold_abs_gbp":r["abs"],"escalation_sla_days":r["sla"],"jira_epic":r["epic"],"emir_flag":r["emir"],"self_correct_days":r["self_correct"],"ml_model_id":r["model"],"active":True},f)
D3S_RECS=[("D3S_CEQ_001","D3S CEQ Break Recon","Cash Equities","D3S-CEQ","CEQ","EQ-BREAKS",False,0.005,300000,3,"rf_ceq",2),("D3S_LND_001","D3S LnD Break Recon","Loans & Deposits","D3S-LND","LND","LND-BREAKS",False,0.001,500000,5,"rf_lnd",0),("D3S_MTN_001","D3S MTN Break Recon","Medium Term Notes","D3S-MTN","MTN","MTN-BREAKS",False,0.002,750000,7,"rf_mtn",3),("D3S_OTC_001","D3S OTC Break Recon","OTC Derivatives","D3S-OTC","OTC","OTC-BREAKS",True,0.0005,250000,1,"rf_otc",0)]
for (rec_id,rec_name,asset_class,src_platform,d3s_code,epic,emir,pct,abs_val,sla,model,sc) in D3S_RECS:
    with open(os.path.join(OUT_DIR,f"{rec_id}.yaml"),"w") as f:
        yaml.dump({"rec_id":rec_id,"rec_name":rec_name,"source_platform":src_platform,"asset_class":asset_class,"d3s_asset_class":d3s_code,"threshold_type":"HYBRID","threshold_pct":pct,"threshold_abs_gbp":abs_val,"escalation_sla_days":sla,"jira_epic":epic,"emir_flag":emir,"self_correct_days":sc,"ml_model_id":model,"active":True},f)
print(f"Generated {len(TLM_RECS)+len(DUCO_RECS)+len(D3S_RECS)} rec configs")
